version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "chalk"
      - dependency-name: "glob"
      - dependency-name: "rimraf"
      - dependency-name: "vitest"
      - dependency-name: "lint-staged"
      - dependency-name: "minimatch"